const axios = require("axios");

exports.generateEmailTemplate = async (purpose, recipientName, tone) => {
  const startTime = Date.now();

  let prompt = "";

  if (tone.toLowerCase() === "polite") {
    prompt = `Write a short, polite and friendly email to ${recipientName} about ${purpose}.`;
  } else if (tone.toLowerCase() === "professional") {
    prompt = `Write a short, professional and formal email to ${recipientName} regarding ${purpose}.`;
  } else {
    prompt = `Write a short email to ${recipientName} about ${purpose}.`;
  }

  try {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }]
          }
        ]
      },
      {
        headers: {
          "Content-Type": "application/json"
        }
      }
    );

    const emailText =
      response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!emailText) {
      throw new Error("No text generated by Gemini");
    }

    const endTime = Date.now();

    return {
      email: emailText.trim(),
      ai_response_time_ms: endTime - startTime
    };

  } catch (error) {
    console.error("Gemini API Error:", error.response?.data || error.message);

    // ❗ fallback (so frontend never breaks)
    return {
      email: "Gemini AI is currently unavailable. Please try again later.",
      ai_response_time_ms: 0
    };
  }
};
